services:
  - type: web
    name: bot-kurier
    runtime: docker
    plan: free
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: RETAIL_URL
        sync: false
      - key: RETAIL_KEY
        sync: false
      - key: PORT
        value: 10000
